services:
  microsoftrewardspilot:
    build: .
    container_name: microsoftrewardspilot
    restart: unless-stopped
    volumes:
      ### Replace "/path/to/" with the actual path to where you want to save the files on your local machine.
      - /Users/bluesky/MicrosoftRewardsPilot/src/accounts.json:/usr/src/microsoftrewardspilot/dist/accounts.json
      - /Users/bluesky/MicrosoftRewardsPilot/src/config.json:/usr/src/microsoftrewardspilot/dist/config.json 
      - /Users/bluesky/MicrosoftRewardsPilot/src/sessions:/usr/src/microsoftrewardspilot/dist/browser/sessions # Optional, saves your login session
    environment:
      - NODE_ENV=production
      - CRON_SCHEDULE=0 9,16 * * * # Customize your schedule, use crontab.guru for formatting
      - RUN_ON_START=true # Runs the script on container startup
      - TZ=Asia/Tokyo # Set your timezone for proper scheduling